name: Simulasi CI/CD Pipeline - Enhanced

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Tambahkan trigger manual dari GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        echo 
        pip install -r requirements.txt

    - name: Jalankan aplikasi dan simulasi akses
      run: |
        echo "🚀 Menjalankan aplikasi dan menguji endpoint untuk tripedia asia"
        python main.py &  # jalankan background
        sleep 3           # tunggu server siap
        RESPONSE=$(curl -s http://localhost:5000 || echo "Gagal mengakses endpoint")
        echo "📦 Hasil respons dari API: $RESPONSE"

    - name: Simulasi sukses
      if: success()
      run: echo "✅ CI/CD berhasil disimulasikan tanpa deploy ke cloud karena issue billing gcp."

    - name: Clean up proses Flask
      run: |
        echo 
        pkill -f "python main.py" || echo 
